
import java.awt.*;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
public class UseCycle extends javax.swing.JFrame implements ItemListener {

    String s;
    static long sr;
     JComboBox stands;
    public UseCycle() {
       initComponents();
    
    }
   
 
 
/*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        lb1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        lb5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setOpaque(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Braham Sarovar Kurukshetra", "Congress Bhawan, Sec-13, Kurukshetra", "LNJP Hospital, Kurukshetra", "MC office Pehowa", "Mini Sectt. Sec-10, Kurukshetra", "New Bus Stand, Kurukshetra", "Parakit Pipli, Kurukshetra", "Sannihit Sarovar", "Satkar Bhojnalya Kurukshetra", "SDM Office, Pehowa", "Testing Stand", " " }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        lb1.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        lb1.setText("Choose Your Present Station");

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cycle_Number", "Cycle_Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(340, 80, 537, 200);
        getContentPane().add(lb5);
        lb5.setBounds(95, 744, 581, 47);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setOpaque(false);

        lb2.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        lb2.setText("Proceed Further for issuing cycle...");

        lb3.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        lb3.setText("Enter Your Card Number");

        jLabel1.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel1.setText("Enter Available Cycle Number");

        jButton1.setText("Issue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Deposit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(330, 280, 550, 201);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CYMERA_20170718_171938.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 880, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        
        s=(String)evt.getItem();
       long S_ID = 0;
        
        final String JDBC_DRIVER="com.mysql.jdbc.Driver";
        final String DB_URL="jdbc:mysql://localhost/sanjhi_cycle";
        final String USER_NAME="root";
        final String password="";
        
        Connection conn=null;
        PreparedStatement stmt=null;
        ResultSet rs=null;
        try{
           
            Class.forName(JDBC_DRIVER);
             conn=(Connection)DriverManager.getConnection(DB_URL,USER_NAME,password);
            String sql="select Station_Name,Station_ID from stand_record";
                stmt=conn.prepareStatement(sql);
                rs=stmt.executeQuery();
                while(rs.next())
               {
                  String temp;
                  temp=rs.getString("Station_Name");
                  if(temp.equals(s))
                          {
                               S_ID=rs.getLong("Station_ID");
                               break;
                          }
                }
                
             sql="select Cycle_Number,Cycle_Type from cycle_registration where Present_Stand='"+S_ID+"'";
             
             stmt=conn.prepareStatement(sql);
             rs=stmt.executeQuery();
             table1.setModel(DbUtils.resultSetToTableModel(rs)); 
            // table1.setRowSelectionAllowed(true);
            
        }
        catch(Exception er)
        {
          JOptionPane.showMessageDialog(this, er);
        }
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UseCycle uc=new UseCycle();
        
        
       String card_num=tf1.getText();
       String cycle_num=tf2.getText();
       
       long num1=Long.parseLong(card_num);
       long num2=Long.parseLong(cycle_num);
       long S_ID=0;
       
       String sql1=null,sql2=null,sql3=null,first_use=null,out_status=null;
       
       final String JDBC_DRIVER="com.mysql.jdbc.Driver";
        final String DB_URL="jdbc:mysql://localhost/sanjhi_cycle";
        final String USER_NAME="root";
        final String password="";
        
        Connection conn=null;
        PreparedStatement stmt1=null,stmt2=null,stmt3=null;
      ResultSet rs1=null,rs2=null,rs3=null;
      String t1="false",t2="true";

        try{
              conn=(Connection)DriverManager.getConnection(DB_URL,USER_NAME,password);
               sql3="select Station_Name,Station_ID from stand_record";
                stmt3=conn.prepareStatement(sql3);
                rs3=stmt3.executeQuery();
                while(rs3.next())
               {
                  String temp;
                  temp=rs3.getString("Station_Name");
                  if(temp.equals(s))
                          {
                             
                            S_ID=rs3.getLong("Station_ID");
                           
                            break;
                          }
               }
            sql1="select Card_Number,First_Use,Out_Status from member_registration_form where Card_Number='"+num1+"'";
            sql2="select Cycle_Number from cycle_registration where Present_Stand='"+S_ID+"' and Cycle_Number='"+num2+"'";
           
             stmt1=conn.prepareStatement(sql1);
             stmt2=conn.prepareStatement(sql2);
           
             rs1=stmt1.executeQuery();
             rs2=stmt2.executeQuery();
             
             long get_num1=0,get_num2=0;
             while(rs1.next())
             {
                 get_num1=rs1.getLong("Card_Number");
                 if(get_num1==num1){
                     first_use=rs1.getString("First_Use");
                     out_status=rs1.getString("Out_Status");
                     break;}
             }
             
              while(rs2.next())
             {
                 get_num2=rs2.getLong("Cycle_Number");
                 if(get_num2==num2)
                     break;
             }
              
             // lb5.setText(get_num1+" "+num1+" "+get_num2+" "+num2);
              DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd hh:mm:ss");
              Date date = new Date();

              
            if(get_num1==num1 && get_num2==num2 && out_status.equals("false"))
            {
                try{
               
                
                sql3="update cycle_registration set AVL_Flag='"+t1+"',Present_Stand='ON_THE_WAY' where Cycle_Number='"+get_num2+"' ";
                stmt3=conn.prepareStatement(sql3);
                stmt3.execute();
                
               
                
                
                sql3="insert into use_cycle_record values(?,?,?,?,?,?)";
                stmt3=conn.prepareStatement(sql3);
                
                stmt3.setString(1,num2+"");
                stmt3.setString(2,num1+"");
                stmt3.setString(3,S_ID+"");
                stmt3.setString(4,dateFormat.format(date));
                stmt3.setString(5,"On The Way");
                stmt3.setString(6,"NULL");
                stmt3.execute();
                 
                
                if(first_use.equals("null") || first_use.equals("Null") || first_use.equals("NULL"))
                    sql3="update member_registration_form set Out_Status='"+t2+"',Last_Use='"+dateFormat.format(date)+"',"
                            + "First_Use='"+dateFormat.format(date)+"' where Card_Number='"+get_num1+"' ";
                else
                     sql3="update member_registration_form set Out_Status='"+t2+"',Last_Use='"+dateFormat.format(date)+"'"
                        + " where Card_Number='"+get_num1+"' ";
               stmt3=conn.prepareStatement(sql3);
                stmt3.execute();
               
              
                
                stmt3=conn.prepareStatement(sql3);
                stmt3.execute();
                JOptionPane.showMessageDialog(null, "cycle issued successfully");
                }
                catch(Exception er)
                {
                    JOptionPane.showMessageDialog(null,er);
                }
                
               
            }
            else{
                if(out_status.equals("true"))
                    JOptionPane.showMessageDialog(null,"Person has already one cycle issued");
                else
                 JOptionPane.showMessageDialog(null,"either Card no is not valid or"
                      + " accessed cycle is not present at this stand.");
            }
        }
        catch(Exception er)
        {
            JOptionPane.showMessageDialog(null, er);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       String card_num=tf1.getText();
       String cycle_num=tf2.getText();
       
       long num1=Long.parseLong(card_num);
       long num2=Long.parseLong(cycle_num);
       long S_ID=0;
       
        final String JDBC_DRIVER="com.mysql.jdbc.Driver";
        final String DB_URL="jdbc:mysql://localhost/sanjhi_cycle";
        final String USER_NAME="root";
        final String password="";
        
        Connection conn=null;
        PreparedStatement stmt1=null,stmt2=null,stmt3=null;
        ResultSet rs1=null,rs2=null,rs3=null;
        String sql1,sql2,sql3,t1="false",t2="true";
        
         DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
              Date date = new Date();
        
       
        
        try{
            String temp1 ="Null",temp2="ON_THE_WAY",present_stand=null;
             conn=(Connection)DriverManager.getConnection(DB_URL,USER_NAME,password);
             
              sql1="select Card_Number from member_registration_form where Card_Number='"+num1+"'";
              sql2="select Cycle_Number,Present_Stand from cycle_registration where Present_Stand='"+temp2+"' and Cycle_Number='"+num2+"'";
              
             stmt1=conn.prepareStatement(sql1);
             stmt2=conn.prepareStatement(sql2);
           
             rs1=stmt1.executeQuery();
             rs2=stmt2.executeQuery();
             
             
             long get_num1=0,get_num2=0;
             while(rs1.next())
             {
                 get_num1=rs1.getLong("Card_Number");
                 if(get_num1==num1){
                     break;}
             }
             
              while(rs2.next())
             {
                 get_num2=rs2.getLong("Cycle_Number");
                 if(get_num2==num2)
                 {
                     present_stand=rs2.getString("Present_Stand");
                     
                     break;
                 }
             }
             
                    
              
                
           
               if(get_num1==num1 && get_num2==num2 && present_stand.equals(temp2))
            {
             sql1="select * from use_cycle_record where Card_Number='"+num1+"' and Cycle_Number='"+num2+"'";
             stmt1=conn.prepareStatement(sql1);
             rs1=stmt1.executeQuery();
             while(rs1.next())
             {              
                      temp1=rs1.getString("Issued_On");  
             }
             
               
                
                sql3="select Station_Name,Station_ID from stand_record";
                stmt3=conn.prepareStatement(sql3);
                rs3=stmt3.executeQuery();
                while(rs3.next())
               {
                  String temp;
                  temp=rs3.getString("Station_Name");
                  if(temp.equals(s))
                          {
                               lb5.setText(get_num1+" "+num1+" "+get_num2+" "+num2);
                            S_ID=rs3.getLong("Station_ID");
                           
                            break;
                          }
                }
                
                sql2="update cycle_registration set AVL_Flag='"+t2+"',Present_Stand='"+S_ID+"' where Cycle_Number='"+num2+"' ";
                stmt2=conn.prepareStatement(sql2);
                stmt2.execute();
                
                 sql2="update member_registration_form set Out_Status='"+t1+"' where Card_Number='"+num1+"' ";
                stmt2=conn.prepareStatement(sql2);
                stmt2.execute();
                
            sql2="update use_cycle_record set Issued_On='"+temp1+"',Deposited_On_Station='"+S_ID+"',"
                    + "Date_Of_Deposit='"+dateFormat.format(date)+"' where Issued_On='"+temp1+"' and Cycle_Number='"+num2+"' " ;
             stmt2=conn.prepareStatement(sql2);
             stmt2.execute();
             JOptionPane.showMessageDialog(null,"Deposit Complete");
            }
                else{
                
                 JOptionPane.showMessageDialog(null,"either Card no is not valid or"
                         + " this cycle was not issued");
            }
               
        }
         catch(Exception er)
        {
            JOptionPane.showMessageDialog(null, er);
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UseCycle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UseCycle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UseCycle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UseCycle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UseCycle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb5;
    private javax.swing.JTable table1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables

    private void itemStateChanges() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void itemStateChanged(ItemEvent ie) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
